language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
node_js:
  - '10'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
